### ISSUE TITLE
Impound Lot Modifications

### ISSUE THREAD

**Issue by NoLoveOrange** [LukeWasTakenn/luke_garages#107]
When a car goes to the impound lot and I take it out of there it comes sometimes with a different color and a nenon light under the car

**Comment by LukeWasTakenn** [comment]
ox_lib is the resource that handles applying vehicle mods. I've never encountered this issue so make sure it's up to date.

**Comment by TheZahamar** [comment]
I also have the same problem, it usually happens when you buy the vehicle fresh

**Comment by meltynetv2** [comment]
> I also have the same problem, it usually happens when you buy the vehicle fresh

> When a car goes to the impound lot and I take it out of there it comes sometimes with a different color and a nenon light under the car

I had this issue, but fixed it. It was due to the old information saved for vehicles not matching up with the new way ox_lib checks for vehicle neons. If you look and compare the data in your database with the old data you will see the "neonEnabled" changed how it stores that data. So when you try to set the vehicle and it uses the old data, it thinks you have all neons enabled because of it. 

As for the color of the vehicle changing, not sure and that's not really possible if your data in your DB is correct and your SetVehicleProperties is correct.

As for how do you revert this, well sadly once you spawn the vehicle and store it again with the neons enabled, you will need to manually go through your database and change every "neonEnabled" value to the new values or remove them completely. This was a headache for me, and I wish you all good luck in fixing this. But yeah if you know what you're doing you will see the problem instantly. 

Is there a way to fix the SetVehicleProperties? Yes, but pointless as ox_lib is constantly updating and you would need to change that part of code EVERY time and it's just easier to adapt to the new format. Hope this shined some light on the situation.

**Comment by LukeWasTakenn** [comment]
> but pointless as ox_lib is constantly updating and you would need to change that part of code EVERY time and it's just easier to adapt to the new format

Or you could just PR the fix to ox_lib instead...

**Comment by meltynetv2** [comment]
> > but pointless as ox_lib is constantly updating and you would need to change that part of code EVERY time and it's just easier to adapt to the new format
> 
> Or you could just PR the fix to ox_lib instead...

Yeah I don't have much experience with GitHub, so I am not sure what a PR is tbh sorry. I would say there really isn't a fix. It would just be using the new format of ox_lib and change the existing "neonEnabled" data to the new format in your MySQL DB. or you can just edit the ox_lib, but I don't think its a problem tbh with ox_lib, just a new way to store the data and you should adapt to it.

I believe the problem here above is they are storing the new vehicle purchases with the es_extended method and not the ox_lib which is what luke_garages uses now I believe, I could be wrong. With that being said it stores the wrong data as es_extended method is not 100% the same as ox_libs. And as well reason it spawns with neons is due to the change in the format it stores that data with.

**Comment by NoLoveOrange** [comment]
I tried to replace old ox_lib with the latest update and download again Luke garages the latest update, but it is still adding neon enabled to the database, I didn’t understand what I should do to fix it instead of manually change every vehicle, I’m not talking about the vehicles that exist already in the database because that one’s I can repair but the new ones that will come. Not know if I’m making myself clear
