### ISSUE TITLE
Car disappering after explosion

### ISSUE THREAD

**Issue by MacacoSensual** [LukeWasTakenn/luke_garages#56]
Do the cars go somewhere after they get totaled?
Also as another user as pointed out i seem to have issues with some parts of the car names showing up as Null.
Thanks in advance and great work.

**Comment by LukeWasTakenn** [comment]
I actually haven't tested explosions at all, now that I think about it it may cause issues because the entity isn't technically getting deleted from the world.

And I'm not sure what's going on with the car names, I don't even know if it's an issue related to my resource or the car's meta files or something

**Comment by LukeWasTakenn** [comment]
Resolved in #71.
