### ISSUE TITLE
Addon Cars "NULL NULL"

### ISSUE THREAD

**Issue by Zzeyy** [LukeWasTakenn/luke_garages#69]
![image](https://user-images.githubusercontent.com/97387354/157301085-b64ba9f7-7312-4c42-ba9c-0d0b52073671.png)

Why are addon cars called "NULL NULL" in the garage menu?

And also why does it say "Undefined" below some of the buttons?

![image](https://user-images.githubusercontent.com/97387354/157301156-da56934c-42dc-40cc-8dc3-81508bf41303.png)

**Comment by LukeWasTakenn** [comment]
You need to add the addon cars text entries into `client/vehicle_names.lua`

If you've already done this then a similar issue was reported here: https://github.com/LukeWasTakenn/luke_garages/issues/48

The undefined issue seems to be related to the zf_context resource, not sure what it would be caused by.
