### ISSUE TITLE
bug when you active the config get into the vehicle

### ISSUE THREAD

**Issue by inahokaizuki** [LukeWasTakenn/luke_garages#93]
Config.TeleportToVehicle = true 
When you active this on , people get problem like the car fuel broken then u must to call mechanic to fix it..
then if fuel not broken , the engine was broken , its same must to call mechanic but there is no bug about car going to impound

Config.TeleportToVehicle = false
there is no bug about broken vehicle anymore
but there is a bug when you try to save your vehicle its going to impound ... , ( its happen when you try to buy vehicle esx_vehicleshop then your going to save it , if you done from the impound and get your vehicle , then you saved it , its fine, its just always getting like that from the first car you buy it into vehicle impound

**Comment by inahokaizuki** [comment]
something the car spawn with the different Z coordinate , 
example : 
i spawn sultanrs with z = 4.02 
and i spawn blista with same coords , its have the different z coords.. , sorry for my bad english by the way, if u can fix the every car have the same z coords its will be nice and fix the config.TeleportVehicle = true bug

**Comment by LukeWasTakenn** [comment]
> When you active this on , people get problem like the car fuel broken then u must to call mechanic to fix it..
then if fuel not broken , the engine was broken

I can't reproduce this. Fuel applies and saves properly when taking the vehicle in and out.

Which leads me to believe that another resource that you have is conflicting with the garages.

> something the car spawn with the different Z coordinate

Different Z coordinate has nothing to do with this.

> its have the different z coords..

Yes because blista is not the same height as the sultan rs

>  if u can fix the every car have the same z coords its will be nice and fix the config.TeleportVehicle = true bug

That would require defining an offset for *every* single vehicle in the game and also for the addon vehicles, and no, fixing the Z coordinate won't magically fix your vehicle props not applying correctly.

**Comment by inahokaizuki** [comment]
yeah i found the bug its because the vehicle failure i use esx_vehiclefailure
